const RESET_BOARD = "RESET_BOARD";
const OPEN_CELL = "OPEN_CELL";
const SWITCH_CELL_FLAG = "SWITCH_CELL_FLAG";
const LOAD_GAME = "LOAD_GAME"

export { RESET_BOARD, OPEN_CELL, SWITCH_CELL_FLAG, LOAD_GAME };
