# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1c921750d46b92fb0bab941ef3295c3a954fe3bddcf6a08b152aea1e0d8c59b119bcbd00820656738273b40d91debe3bb8fe38d1d70993613381368c52f78d87

test:
  secret_key_base: 9e02be4930201e16639e568f0e5a42990966b0cb74833093d65e32f1ad8e502689fd369b7ca147f23c3fa7c4c2494515dac64713ee106e6333dd4d9e3f92dff1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
